# Generated by Django 5.2.6 on 2025-09-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud', models.CharField(choices=[('aws', 'AWS'), ('gcp', 'Google Cloud'), ('azure', 'Azure')], max_length=50)),
                ('product', models.CharField(choices=[('s3', 'Amazon S3'), ('gcs', 'Google Cloud Storage'), ('blobStorage', 'Azure Blob Storage'), ('sftp', 'SFTP'), ('bigquery', 'BigQuery'), ('snowflake', 'Snowflake'), ('databricks', 'Databricks'), ('redshift', 'Amazon Redshift')], max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('auth', models.JSONField(default=dict)),
                ('bucket_name', models.CharField(max_length=100)),
                ('bucket_type', models.CharField(blank=True, help_text='Type of the bucket(optional)', max_length=50, null=True)),
                ('path', models.CharField(blank=True, help_text='Path within the bucket(optional)', max_length=255, null=True)),
                ('created_by', models.CharField(default='system', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default='system', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for the source', max_length=100, unique=True)),
                ('cloud', models.CharField(choices=[('aws', 'AWS'), ('gcp', 'Google Cloud'), ('azure', 'Azure'), ('external', 'External')], max_length=50)),
                ('product', models.CharField(choices=[('s3', 'Amazon S3'), ('gcs', 'Google Cloud Storage'), ('blobStorage', 'Azure Blob Storage'), ('sftp', 'SFTP')], max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('bucket_name', models.CharField(max_length=100)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('config', models.JSONField(default=dict)),
                ('created_by', models.CharField(default='system', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default='system', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
