# Generated by Django 5.2.6 on 2025-09-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='bucket_name',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='bucket_type',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='path',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='source',
            name='bucket_name',
        ),
        migrations.RemoveField(
            model_name='source',
            name='config',
        ),
        migrations.RemoveField(
            model_name='source',
            name='path',
        ),
        migrations.RemoveField(
            model_name='source',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='source',
            name='auth',
            field=models.JSONField(default=dict, help_text='JSON object with authentication details'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='auth',
            field=models.JSONField(default=dict, help_text='JSON object with authentication details'),
        ),
        migrations.AlterField(
            model_name='source',
            name='cloud',
            field=models.CharField(choices=[('aws', 'AWS'), ('gcp', 'Google Cloud'), ('azure', 'Azure')], max_length=50),
        ),
        migrations.AlterField(
            model_name='source',
            name='product',
            field=models.CharField(choices=[('s3', 'Amazon S3'), ('gcs', 'Google Cloud Storage'), ('blobStorage', 'Azure Blob Storage'), ('sftp', 'SFTP'), ('bigquery', 'BigQuery'), ('snowflake', 'Snowflake'), ('databricks', 'Databricks'), ('redshift', 'Amazon Redshift')], max_length=50),
        ),
    ]
